/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminProductsRouteImport } from './routes/_admin.products'
import { Route as AdminOrdersRouteImport } from './routes/_admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/_admin.messages'
import { Route as AdminHeroVideosRouteImport } from './routes/_admin.hero-videos'
import { Route as AdminDeliveryRouteImport } from './routes/_admin.delivery'
import { Route as AdminCustomersRouteImport } from './routes/_admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/_admin.coupons'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroVideosRoute = AdminHeroVideosRouteImport.update({
  id: '/hero-videos',
  path: '/hero-videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/coupons': typeof AdminCouponsRoute
  '/customers': typeof AdminCustomersRoute
  '/delivery': typeof AdminDeliveryRoute
  '/hero-videos': typeof AdminHeroVideosRoute
  '/messages': typeof AdminMessagesRoute
  '/orders': typeof AdminOrdersRoute
  '/products': typeof AdminProductsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/coupons': typeof AdminCouponsRoute
  '/customers': typeof AdminCustomersRoute
  '/delivery': typeof AdminDeliveryRoute
  '/hero-videos': typeof AdminHeroVideosRoute
  '/messages': typeof AdminMessagesRoute
  '/orders': typeof AdminOrdersRoute
  '/products': typeof AdminProductsRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/coupons': typeof AdminCouponsRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/delivery': typeof AdminDeliveryRoute
  '/_admin/hero-videos': typeof AdminHeroVideosRoute
  '/_admin/messages': typeof AdminMessagesRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/coupons'
    | '/customers'
    | '/delivery'
    | '/hero-videos'
    | '/messages'
    | '/orders'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/coupons'
    | '/customers'
    | '/delivery'
    | '/hero-videos'
    | '/messages'
    | '/orders'
    | '/products'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/coupons'
    | '/_admin/customers'
    | '/_admin/delivery'
    | '/_admin/hero-videos'
    | '/_admin/messages'
    | '/_admin/orders'
    | '/_admin/products'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/messages': {
      id: '/_admin/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/hero-videos': {
      id: '/_admin/hero-videos'
      path: '/hero-videos'
      fullPath: '/hero-videos'
      preLoaderRoute: typeof AdminHeroVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/delivery': {
      id: '/_admin/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/coupons': {
      id: '/_admin/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminHeroVideosRoute: typeof AdminHeroVideosRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminHeroVideosRoute: AdminHeroVideosRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
